# Generated by Django 4.2.5 on 2023-09-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lessonview',
            name='view_time_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
