# Generated by Django 4.2.5 on 2023-09-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_lesson_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
